Repository yseop/vscode-yseopml, pull requests merged in 2018-10, with the labels that each got.

#33 fix(color): fix syntax coloring of comments in function arguments
  client/syntaxes/yml.tmLanguage.json
Labels: bug

#34 fix(properties): replaced YML settings title
  client/package.json
Labels: bug

#37 feat(yseopCliCommands): use Yseop CLI batch + compile as VSCode command
  client/CHANGELOG.md
  client/package.json
  client/src/extension.ts
Labels: enhancement

#38 feat(cliCmds): new CLI commands in VSCode
  client/CHANGELOG.md
  client/package.json
  client/src/extension.ts
Labels: enhancement

#39 release(1.2.0): version 1.2.0
  client/CHANGELOG.md
  client/package-lock.json
  client/package.json
  client/server/package-lock.json
  client/server/package.json
  client/src/extension.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: help wanted

#42 feat(UX): improve user experience
  client/package.json
  client/src/extension.ts
  package.json
Labels: enhancement

#41 feat(releaseScripts): basic script to produce a release branch
  release.sh
Labels: enhancement

#43 Release/1.2.1
  client/CHANGELOG.md
  client/package-lock.json
  client/package.json
  client/server/package-lock.json
  client/server/package.json
  client/src/extension.ts
  package-lock.json
  package.json
  release.sh
  server/package-lock.json
  server/package.json
Labels: help wanted
